# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
            ],
        ),
    ]
